CREATE FILE FORMAT IF NOT EXISTS RAW.HN.FF_JSON TYPE = JSON;
CREATE STAGE IF NOT EXISTS RAW.HN.STG_HN FILE_FORMAT = RAW.HN.FF_JSON;

CREATE TABLE IF NOT EXISTS RAW.HN.STORIES (
  payload VARIANT, _file STRING,
  _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE IF NOT EXISTS RAW.HN.COMMENTS (
  payload VARIANT, _file STRING,
  _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE IF NOT EXISTS RAW.HN.INGESTION_STATE (
  source STRING, high_watermark NUMBER, updated_at TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS RAW.HN.COMMENT_SCORES (
  comment_id NUMBER, sentiment FLOAT, topic STRING, scored_by STRING,
  scored_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
