-- One-time manual bootstrap, run as ACCOUNTADMIN before `terraform apply`
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TF_ADMIN;
GRANT ROLE SYSADMIN, SECURITYADMIN TO ROLE TF_ADMIN;
GRANT CREATE ROLE, CREATE USER, CREATE RESOURCE MONITOR ON ACCOUNT TO ROLE TF_ADMIN;

CREATE USER IF NOT EXISTS TF_USER
  DEFAULT_ROLE = TF_ADMIN
  RSA_PUBLIC_KEY = '<contents of tf_user.pub without BEGIN/END lines>';
GRANT ROLE TF_ADMIN TO USER TF_USER;

-- Account-wide safety net
CREATE RESOURCE MONITOR IF NOT EXISTS ACCOUNT_GUARD
  WITH CREDIT_QUOTA = 15 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;
ALTER ACCOUNT SET RESOURCE_MONITOR = ACCOUNT_GUARD;
